apiVersion: v1
kind: List
items:
- apiVersion: tekton.dev/v1alpha1
  kind: Task
  metadata:
    name: sign-task
  spec:
    inputs:
      resources:
      - name: source-image
        type: image
      - name: signed-image
        type: image
    steps:
    - name: sign-image
      securityContext: {}
      image: kabanero/kabanero-utils:0.8.0
      command: ['/bin/bash']
      args:
        - -c
        - |
          REPO=`cat /etc/gpg/registry`
          if [[ $(inputs.resources.signed-image.url) != $REPO/* ]]
          then
             echo "The specified signed image repository does not match the name of the repository in image-signing-config secret resource. The repository name should start with $REPO, Specified signed image name is $(inputs.resources.signed-image.url)"
           exit 1
          fi
          gpg --import /etc/gpg/secret.asc
          SIGNBY=`gpg --list-keys|sed -n -e "/.*<.*>.*/p"|sed -e "s/^.*<\(.*\)>.*$/\1/"`
          skopeo copy --dest-tls-verify=false --src-tls-verify=false --remove-signatures --sign-by $SIGNBY "docker://$(inputs.resources.source-image.url)" "docker://$(inputs.resources.signed-image.url)"
          RESULT=$?
          if [ $RESULT -ne 0 ]
          then
             echo "sign-image failed. exit code : $RESULT"
             exit $RESULT
          fi
      volumeMounts:
        - name: image-signing-config
          mountPath: /etc/gpg
        - name: registries-d-dir
          mountPath: /etc/containers/registries.d
    volumes:
      - name: image-signing-config
        secret:
          secretName: image-signing-config
      - name: registries-d-dir
        configMap:
          name: registries-d
- apiVersion: tekton.dev/v1alpha1
  kind: Pipeline
  metadata:
    name: sign-pipeline
  spec:
    resources:
      - name: source-image
        type: image
      - name: signed-image
        type: image
    tasks:
      - name: standalone-sign
        taskRef:
          name: sign-task
        resources:
          inputs:
          - name: source-image
            resource: source-image
          - name: signed-image
            resource: signed-image
