// +build !ignore_autogenerated

// Code generated by operator-sdk. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImageSigning) DeepCopyInto(out *ImageSigning) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImageSigning.
func (in *ImageSigning) DeepCopy() *ImageSigning {
	if in == nil {
		return nil
	}
	out := new(ImageSigning)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ImageSigning) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImageSigningList) DeepCopyInto(out *ImageSigningList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ImageSigning, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImageSigningList.
func (in *ImageSigningList) DeepCopy() *ImageSigningList {
	if in == nil {
		return nil
	}
	out := new(ImageSigningList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ImageSigningList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImageSigningSpec) DeepCopyInto(out *ImageSigningSpec) {
	*out = *in
	if in.Identity != nil {
		in, out := &in.Identity, &out.Identity
		*out = new(SignatureIdentity)
		**out = **in
	}
	if in.Keypair != nil {
		in, out := &in.Keypair, &out.Keypair
		*out = new(SignatureKeypair)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImageSigningSpec.
func (in *ImageSigningSpec) DeepCopy() *ImageSigningSpec {
	if in == nil {
		return nil
	}
	out := new(ImageSigningSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImageSigningStatus) DeepCopyInto(out *ImageSigningStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImageSigningStatus.
func (in *ImageSigningStatus) DeepCopy() *ImageSigningStatus {
	if in == nil {
		return nil
	}
	out := new(ImageSigningStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SignatureIdentity) DeepCopyInto(out *SignatureIdentity) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SignatureIdentity.
func (in *SignatureIdentity) DeepCopy() *SignatureIdentity {
	if in == nil {
		return nil
	}
	out := new(SignatureIdentity)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SignatureKeypair) DeepCopyInto(out *SignatureKeypair) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SignatureKeypair.
func (in *SignatureKeypair) DeepCopy() *SignatureKeypair {
	if in == nil {
		return nil
	}
	out := new(SignatureKeypair)
	in.DeepCopyInto(out)
	return out
}
